namespace: fleet-mc-helm-example
targetCustomizations:
- name: aks
  helm:
    values:
      replicas: 5
  clusterSelector:
    matchLabels:
      cloud: aks

- name: eks
   helm:
    values:
      replicas: 1
  clusterSelector:
    matchLabels:
      cloud: eks
