targetCustomizations:
- name: aks
  helm:
    values:
      replicas: 5
  clusterSelector:
    matchLabels:
      cloud: aks
- name: eks
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 1
  clusterSelector:
    matchLabels:
      cloud: eks
- name: local
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 3     
  clusterGroup: default
