targetCustomizations:
- name: aks
  helm:
    values:
      replicas: 3
  clusterSelector:
    matchLabels:
      cloud: aks
- name: eks
  helm:
    values:
      serviceType: NodePort
      replicas: 1
  clusterSelector:
    matchLabels:
      cloud: eks
- name: local
  helm:
    values:
      serviceType: NodePort
      replicas: 2     
  clusterGroup: default
